Fiddle with `pos` in `funcScope.LookupParent` for Go 1.22 breakage
First I tried changing `funcScope.LookupParent` to use the starting
brace ("{") of the function, but that didn't work for redeclarations:

    $ go test -v
        analysistest.go:522: gocapturedrefrace/testdata/shadow.go:38:6: unexpected diagnostic: captured reference err in goroutine closure
        analysistest.go:522: gocapturedrefrace/testdata/shadow.go:39:14: unexpected diagnostic: captured reference err in goroutine closure
        analysistest.go:522: gocapturedrefrace/testdata/shadow.go:47:3: unexpected diagnostic: captured reference err in goroutine closure
        analysistest.go:522: gocapturedrefrace/testdata/shadow.go:48:6: unexpected diagnostic: captured reference err in goroutine closure
        analysistest.go:522: gocapturedrefrace/testdata/shadow.go:49:14: unexpected diagnostic: captured reference err in goroutine closure
        analysistest.go:522: gocapturedrefrace/testdata/shadow.go:66:3: unexpected diagnostic: captured reference err1 in goroutine closure
        analysistest.go:522: gocapturedrefrace/testdata/shadow.go:67:3: unexpected diagnostic: captured reference err2 in goroutine closure
        analysistest.go:522: gocapturedrefrace/testdata/shadow.go:68:6: unexpected diagnostic: captured reference err1 in goroutine closure
        analysistest.go:522: gocapturedrefrace/testdata/shadow.go:68:21: unexpected diagnostic: captured reference err2 in goroutine closure
        analysistest.go:522: gocapturedrefrace/testdata/shadow.go:69:14: unexpected diagnostic: captured reference err1 in goroutine closure
        analysistest.go:522: gocapturedrefrace/testdata/shadow.go:69:20: unexpected diagnostic: captured reference err2 in goroutine closure
    --- FAIL: Test (0.43s)

The commit that breaks the analyzer says:

> Previously, its value was unset (NoPos), but the correct
> value is a point after the signature (FuncType.End) and
> before the body.

(https://github.com/golang/go/commit/a27a525d1b4df74989ac9f6ad10394391fe3eb88)

Recalling that, I tried setting the position to `token.NoPos`, which
fixes the analyser and allows the tests to pass.